FLOWER_NAMES = {

1: ("pink primrose","pembe çuha çiçeği"),
2: ("hard-leaved pocket orchid","cep orkidesi"),
3: ("canterbury bells","canterbury çanı"),
4: ("sweet pea","kokulu bezelye"),
5: ("english marigold","aynısafa"),
6: ("tiger lily","kaplan zambağı"),
7: ("moon orchid","ay orkidesi"),
8: ("bird of paradise","cennet kuşu çiçeği"),
9: ("monkshood","rahip başlığı"),
10: ("globe thistle","küre devedikeni"),
11: ("snapdragon","aslanağzı"),
12: ("colt's foot","öksürük otu"),
13: ("king protea","kral protea"),
14: ("spear thistle","mızrak devedikeni"),
15: ("yellow iris","sarı süsen"),
16: ("globe flower","küre çiçeği"),
17: ("purple coneflower","mor ekinezya"),
18: ("peruvian lily","peru zambağı"),
19: ("balloon flower","balon çiçeği"),
20: ("giant white arum lily","dev beyaz zambak"),
21: ("fire lily","ateş zambağı"),
22: ("pincushion flower","yastık çiçeği"),
23: ("fritillary","fritillaria"),
24: ("red ginger","kırmızı zencefil çiçeği"),
25: ("grape hyacinth","üzüm sümbülü"),
26: ("corn poppy","gelincik"),
27: ("prince of wales feathers","galler prensi tüyü"),
28: ("stemless gentian","gövdəsiz centiyana"),
29: ("artichoke","enginar çiçeği"),
30: ("sweet william","hüsnüyusuf"),
31: ("carnation","karanfil"),
32: ("garden phlox","bahçe floksu"),
33: ("love in the mist","çörek otu çiçeği"),
34: ("mexican aster","meksika papatyası"),
35: ("alpine sea holly","alp dikenli otu"),
36: ("ruby-lipped cattleya","yakut dudaklı orkide"),
37: ("cape flower","kap çiçeği"),
38: ("great masterwort","büyük ustabotu"),
39: ("siam tulip","siyam lalesi"),
40: ("lenten rose","oruç gülü"),
41: ("barbeton daisy","barbeton papatyası"),
42: ("daffodil","nergis"),
43: ("sword lily","glayöl"),
44: ("poinsettia","Atatürk çiçeği"),
45: ("bolero deep blue","bolero çiçeği"),
46: ("wallflower","duvar çiçeği"),
47: ("marigold","kadife çiçeği"),
48: ("buttercup","düğün çiçeği"),
49: ("oxeye daisy","büyük papatya"),
50: ("common dandelion","karahindiba"),
51: ("petunia","petunya"),
52: ("wild pansy","yabani hercai menekşe"),
53: ("primula","çuha çiçeği"),
54: ("sunflower","ayçiçeği"),
55: ("pelargonium","sardunya"),
56: ("bishop of llandaff","llandaff piskoposu çiçeği"),
57: ("gaura","gaura"),
58: ("geranium","turnagagası"),
59: ("orange dahlia","turuncu yıldız çiçeği"),
60: ("pink-yellow dahlia","pembe sarı yıldız çiçeği"),
61: ("cautleya spicata","cautleya"),
62: ("japanese anemone","japon anemonu"),
63: ("black-eyed susan","kara gözlü susan"),
64: ("silverbush","gümüş çalı çiçeği"),
65: ("californian poppy","kaliforniya gelinciği"),
66: ("osteospermum","afrika papatyası"),
67: ("spring crocus","bahar çiğdemi"),
68: ("bearded iris","sakallı iris"),
69: ("windflower","rüzgar çiçeği"),
70: ("tree poppy","ağaç gelinciği"),
71: ("gazania","gazanya"),
72: ("azalea","açelya"),
73: ("water lily","nilüfer"),
74: ("rose","gül"),
75: ("thorn apple","boru çiçeği"),
76: ("morning glory","sabah sefası"),
77: ("passion flower","çarkıfelek"),
78: ("lotus","lotus"),
79: ("toad lily","kurbağa zambağı"),
80: ("anthurium","antoryum"),
81: ("frangipani","frangipani"),
82: ("clematis","akasma"),
83: ("hibiscus","hibiskus"),
84: ("columbine","hasekiküpesi"),
85: ("desert rose","çöl gülü"),
86: ("tree mallow","ağaç ebegümeci"),
87: ("magnolia","manolya"),
88: ("cyclamen","siklamen"),
89: ("watercress","su teresi çiçeği"),
90: ("canna lily","kana zambağı"),
91: ("hippeastrum","amarilis"),
92: ("bee balm","arı melisası"),
93: ("ball moss","top yosun"),
94: ("foxglove","yüksük otu"),
95: ("bougainvillea","begonvil"),
96: ("camellia","kamelya"),
97: ("mallow","ebegümeci"),
98: ("mexican petunia","meksika petunyası"),
99: ("bromelia","bromelya"),
100: ("blanket flower","güneş çiçeği"),
101: ("trumpet creeper","trompet sarmaşığı"),
102: ("blackberry lily","böğürtlen zambağı")

}